name: Node
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: npm  and test
        run: npm test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Upload artifacts
          path: |
            build
